package co.edu.unbosque.accioneselbosque.trazabilidad.model;

public enum TipoEvento {
    // Autenticación
    REGISTRO_INICIADO,
    REGISTRO_EXITOSO,
    REGISTRO_FALLO_ALPACA,
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    CUENTA_BLOQUEADA,
    MFA_ENVIADO,
    MFA_VERIFICADO,
    MFA_FALLIDO,
    MFA_ACTIVADO,
    MFA_DESACTIVADO,
    LOGOUT,
    RECUPERACION_PASSWORD_SOLICITADA,
    PASSWORD_RESETEADA,
    CAMBIO_ESTADO_CUENTA,
    // Perfil
    PERFIL_CONSULTADO,
    PERFIL_ACTUALIZADO,
    PREFERENCIAS_NOTIFICACION_ACTUALIZADAS,
    PREFERENCIAS_OPERACION_ACTUALIZADAS,
    // Suscripción
    SUSCRIPCION_PREMIUM_INICIADA,
    SUSCRIPCION_PREMIUM_FALLIDA,
    SUSCRIPCION_PREMIUM_CANCELADA,
    // Órdenes
    ORDEN_CREADA,
    ORDEN_ENVIADA_ALPACA,
    ORDEN_EJECUTADA,
    ORDEN_CANCELADA,
    ORDEN_ENCOLADA,
    ORDEN_RECHAZADA_FONDOS,
    ORDEN_RECHAZADA_HOLDINGS,
    ORDEN_FALLO_ALPACA,
    PROPUESTA_ORDEN_CREADA,
    PROPUESTA_ORDEN_APROBADA,
    PROPUESTA_ORDEN_RECHAZADA,
    PROPUESTA_ORDEN_FIRMADA,
    COMISIONISTA_ASIGNADO,
    COMISIONISTA_ASIGNACION_FALLIDA,
    ACCESO_DENEGADO_CLIENTE_NO_ASIGNADO,
    // Portafolio / saldo
    FONDOS_SINCRONIZADOS,
    HOLDING_ACTUALIZADO,
    // Mercado
    PRECIO_CONSULTADO,
    CACHE_REFRESCADO
}
